### GET - /api
GET http://localhost:3000/api


### POST - /api/auth/register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Jasmine Doe",
  "email": "jasmine.doe@example.com",
  "password": "12345678"
}


### POST - /api/auth/login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "jasmine.doe@example.com",
  "password": "12345678"
}


### GET - /api/users/profile
GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFkZTFjZDVkYzU0NDNkY2Y4ZDEzNzEiLCJpYXQiOjE3NjAyODM2MjksImV4cCI6MTc2MDM3MDAyOX0.11ESpLH4p5h28nWWvEbacfS5pwX1dH_Zys63uPXeIz8


### POST - /api/snippets
POST http://localhost:3000/api/snippets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFkZTFjZDVkYzU0NDNkY2Y4ZDEzNzEiLCJpYXQiOjE3NjAyODM2MjksImV4cCI6MTc2MDM3MDAyOX0.11ESpLH4p5h28nWWvEbacfS5pwX1dH_Zys63uPXeIz8

{
  "title": "JavaScript Hello World",
  "description": "A simple example demonstrating how to print a message to the console using JavaScript.",
  "tags": ["JavaScript", "Beginner", "Basics"],
  "code": "console.log('Hello, World!');",
  "language": "JavaScript"
}


### GET - /api/snippets
GET http://localhost:3000/api/snippets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFkZTFjZDVkYzU0NDNkY2Y4ZDEzNzEiLCJpYXQiOjE3NjAyODM2MjksImV4cCI6MTc2MDM3MDAyOX0.11ESpLH4p5h28nWWvEbacfS5pwX1dH_Zys63uPXeIz8


### GET - /api/snippets/:ID
GET http://localhost:3000/api/snippets/68ebd22160baebca8543af18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFkZTFjZDVkYzU0NDNkY2Y4ZDEzNzEiLCJpYXQiOjE3NjAyODM2MjksImV4cCI6MTc2MDM3MDAyOX0.11ESpLH4p5h28nWWvEbacfS5pwX1dH_Zys63uPXeIz8


### PUT - /api/snippets/:ID
PUT http://localhost:3000/api/snippets/68ebd22160baebca8543af18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFkZTFjZDVkYzU0NDNkY2Y4ZDEzNzEiLCJpYXQiOjE3NjAyODM2MjksImV4cCI6MTc2MDM3MDAyOX0.11ESpLH4p5h28nWWvEbacfS5pwX1dH_Zys63uPXeIz8

{
  "title": "JavaScript Hello World"
}